version: '2'

services:

#  prometheus:
#    image: prom/prometheus
#    restart: always
#    volumes:
#      - ./prometheus-data:/prometheus-data
#    command:
#      - "--config.file=/prometheus-data/prometheus.yml"
#    ports:
#      - "9090:9090"

  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      GF_SERVER_ROOT_URL: http://prometheus:9090/
    ports:
      - "3000:3000"
